version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3001:3001"
    volumes:
      - .:/opt/app
    command: bash -c 'bin/setup && rails server -b 0.0.0.0 -p 3001'
